### ISSUE TITLE
Compact jsonld paths for new @id's in parameters

### ISSUE THREAD

**Issue by RobinDeBaets** [LinkedSoftwareDependencies/Components-Generator.js#10]
Currently, when creating a new parameter, it's `@id` will equal `<components_id>/<className>#fieldName`. 
In this case, `<components_id>` is the value of the `@id` entry in the `components.jsonld` file.
In a lot of cases, this `@id` can however be compacted even more, which will create cleaner files.

We can use [jsonld-context-parser.js](https://github.com/rubensworks/jsonld-context-parser.js) or [jsonld](https://www.npmjs.com/package/jsonld) to compact this value. However, we should should closely look at which contexts we want to use.

**Comment by rubensworks** [comment]
Done in rewrite
