### ISSUE TITLE
Implement entriesCollection support

### ISSUE THREAD

**Issue by RobinDeBaets** [LinkedSoftwareDependencies/Components-Generator.js#12]
Currently, the [following type](https://componentsjs.readthedocs.io/en/latest/configuration/components/entry_collection/) of configuration is not supported. 
This is something we want to be able to parse/generate.
This is relatively low-priority because not a lot of packages use this functionality, but we should implement it nonetheless.

An example:
```typecript
contextKeyShortcuts: {[shortcut: string]: string};
```
becomes
```json
{  
   "keyRaw":"contextKeyShortcuts",
   "value":{  
      "fields":[  
         {  
            "collectEntries":"cais:contextKeyShortcut",
            "key":"cais:contextKeyShortcut/shortcut",
            "value":"cais:contextKeyShortcut/expanded"
         }
      ]
   }
```
and 
```json
{
  "@id": "cais:contextKeyShortcut",
  "comment": "A context key shortcut entry",
  "range": {
    "@type": "cais:contextKeyShortcut/Entry",
    "parameters": [
      {
        "@id": "cais:contextKeyShortcut/shortcut",
        "comment": "A shortcut string",
        "required": true,
        "unique": true
      },
      {
        "@id": "cais:contextKeyShortcut/expanded",
        "comment": "The full expanded key",
        "required": true,
        "unique": true
      }
    ]
  }
}
```

Implementing this will require some restructuring: fields are currenty parsed in `getFields`, but they only receive their unique `@id` in `getParametersAndArguments` in `AstUtils`.

**Comment by rubensworks** [comment]
This has been supported for a while now.
