### ISSUE TITLE
Update NPM tests

### ISSUE THREAD

**Issue by RobinDeBaets** [LinkedSoftwareDependencies/Components-Generator.js#13]
Currently, the results of the NPM test `@comunica/actor-query-operation-reduced-hash@1.9.0` are incorrect, due to an issue with some dependencies of this version. (See [this issue](https://github.com/comunica/comunica/issues/487)). The test doesn't fail however, because we're checking against an invalid result.

More specifically, the following errors should disappear:
```
error: Did not find a component for superclass AbstractBindingHash
error: We could not find a matching argument for IActorInitRdfDereferencePagedArgs in a superclass
```

Once there is an update of this package, we should update the tests to reflect the correct behaviour. Other tests might fail as well and expected output should be corrected.

**Comment by rubensworks** [comment]
Not applicable anymore due to rewrite.
