### ISSUE TITLE
Only copy necessary context

### ISSUE THREAD

**Issue by RobinDeBaets** [LinkedSoftwareDependencies/Components-Generator.js#15]
Currently, when another component (or in general something that can be referenced by its IRI) is referenced in a constructor argument or field of a constructor argument, we copy all the context entries of its component file. 

However, not all these context entries are necessary to reference to the `@id` of this component. We should create a way to find out which entries are really necessary and only copy those.
An idea would be to create an index of all available contexts and check per package if any of its prefixes is used.

This is low-priority because it's more of an inconvenience than an issue.
However, if our tool is able to detect which are the required contexts, we could expand the fix tool tests to verify an existing `.jsonld` file is not missing a required context entry.

**Comment by rubensworks** [comment]
Not applicable anymore due to rewrite.
