### ISSUE TITLE
Generate bus files

### ISSUE THREAD

**Issue by RobinDeBaets** [LinkedSoftwareDependencies/Components-Generator.js#17]
The tool, in its current form, does not know the concept of a bus class and is not able to generate specific files for them.

An example:
https://github.com/comunica/comunica/blob/39a4513679410f3c986d71750a2fc9c871660607/packages/bus-sparql-parse/components/Bus/SparqlParse.jsonld#L1-L6

**Comment by rubensworks** [comment]
Not applicable anymore due to rewrite.
