### ISSUE TITLE
Avoid moduleRoot option

### ISSUE THREAD

**Issue by RobinDeBaets** [LinkedSoftwareDependencies/Components-Generator.js#19]
All of our CLI tools and Javascript bindings currently have some kind of `moduleRoot` option, a path relative to the root of a package, to resolve dependencies.
This default to the root directory of a package, but in Comunica for example, you should use the value `../../`, because otherwise relevant node modules won't be found and links can not be made.

This is because we use this internally
`let nodeModules = await ComponentsJsUtil.getModuleComponentPaths(directory);`

However, this [utility class](https://github.com/LinkedSoftwareDependencies/Components.js/blob/master/lib/Util.ts) only seems to recurse the subdirectories to search for node modules. In the case of the workspace of Comunica, the node modules are actually located in parent folders.

We should find a way that avoids the users of this tool to have to specify a module root, perhaps by traveling the directory structure upwards?

**Comment by rubensworks** [comment]
Not applicable anymore due to rewrite.
