### ISSUE TITLE
Allow complex default and defaultScoped tags

### ISSUE THREAD

**Issue by RobinDeBaets** [LinkedSoftwareDependencies/Components-Generator.js#20]
Currently, we can put `@default {<value>}` in a comment to indicate the `default` attribute will be set to the string `<value>`. 

In practice however, our `default` attribute can be much more complex:

```json
{
"default": [
  {
    "contextShortcutKey": "source",
    "contextShortcutValue": "@comunica/bus-rdf-resolve-quad-pattern:source"
  },
  {
    "contextShortcutKey": "sources",
    "contextShortcutValue": "@comunica/bus-rdf-resolve-quad-pattern:sources"
  }
]
}
```
A simple solution would be to try to parse the value from the default tag as a JSON string. This might be a bit cumbersome though.
Example:
```
@default {[
  {
    "contextShortcutKey": "source",
    "contextShortcutValue": "@comunica/bus-rdf-resolve-quad-pattern:source"
  },
  {
    "contextShortcutKey": "sources",
    "contextShortcutValue": "@comunica/bus-rdf-resolve-quad-pattern:sources"
  }
]}
```
We're also not sure whether our comment parsing library `comment-parser` can still parse this.

Parsing as JSON is also not the correct thing to do, especially in the case of an `xsd:string`. 
See this example from comunica:
```json
{
  "@id": "cahn:Actor/Http/Native/agentOptions",
  "comment": "The AgentOptions for the HTTP agent as a JSON string",
  "required": false,
  "unique": true,
  "default": "{ \"keepAlive\": true, \"maxSockets\": 5 }",
  "range": "xsd:string"
}
```
Parsing the `default` value as JSON would have been incorrect in this case.

Additionally, we'd like to do the same for `defaultScoped`: add a new tag that users can use in their TypeScript comments and potentially try to parse the value as JSON.

**Comment by rubensworks** [comment]
Default values can be more complex in 3.x
