### ISSUE TITLE
Allow default imports and exports

### ISSUE THREAD

**Issue by RobinDeBaets** [LinkedSoftwareDependencies/Components-Generator.js#21]
Imagine this scenario:
`File1.ts`
```
export default class Actor1 {
}
```
and
`File2.ts`
 ```
import Actor1Alt from "./Actor1";
export default class Actor0 extends Actor1Alt {
}
```

The current version of the tool will not be able to understand this kind of default-import notation and thus can't find the reference to `Actor1Alt` in `File2.ts`. 
Furthermore, the part of the tool that reads the `index.ts` will also not be able to match the `Actor1` component to its file.

We should allow default imports and exports to be used (if they are supported by Components.js).
This is relatively low-priority. No Comunica components use this way of exporting.

After implementing this, additional test cases should be added to the local `test-package1`.

**Comment by rubensworks** [comment]
Supported in 5.x
