### ISSUE TITLE
Problems with optional nested objects

### ISSUE THREAD

**Issue by joachimvh** [LinkedSoftwareDependencies/Components-Generator.js#44]
Example constructor to explain the problems: 
```typescript
constructor(value?: number, options?: { value: number, type: { value: number }}))
```

When running components generator on this, there will be 3 parameters generated, each of them with the same identical URI (ending on `..._value`).

Additionally, the last two (whichare part of the options interface) will not be indicated as being optional. The firstone will be optional as expected.

**Comment by rubensworks** [comment]
Oh, that's not good indeed.
