### ISSUE TITLE
Support Record

### ISSUE THREAD

**Issue by joachimvh** [LinkedSoftwareDependencies/Components-Generator.js#47]
When using `Record<string, string>` instead of e.g. `{ [id: string] : string }` the generator throws the error `Could not load class or interface Record`.

**Comment by rubensworks** [comment]
This is because this resolves to a `type`.
These are not supported since they can become very complex.
I'll see what I can do, but supporting all cases will probably not be feasible.

**Comment by joachimvh** [comment]
This just came up because the linter enforces using Records since the dependencies have been updated 😂 . If it's a big issue we can also think about changing that rule.

**Comment by rubensworks** [comment]
I would suggest that for now. We can then re-enable the rule once this here is fixed.
