### ISSUE TITLE
Constructor argument not generated if interface is "empty"

### ISSUE THREAD

**Issue by joachimvh** [LinkedSoftwareDependencies/Components-Generator.js#50]
Not completely sure what causes this. The problem is with the [LockingResourceStore constructor](https://github.com/solid/community-server/blob/3bd82271b4cb1bebba5ac7431d00bad540a25a88/src/storage/LockingResourceStore.ts#L24):

This is about the second parameter, the [ExpiringResourceLocker](https://github.com/solid/community-server/blob/master/src/util/locking/ExpiringResourceLocker.ts).

When building the config the following constructor parameters get generated:
```json
      "constructorArguments": [
        {
          "@id": "scs:storage/LockingResourceStore#LockingResourceStore_source"
        },
        {
          "fields": []
        }
      ]
```
As you can see the `locks` parameter is missing but there is an empty fields array for some reason.

Even more interesting: if I add a random optional function to the ExpiringResourceLocker interface I do get the correct result:
```json
      "constructorArguments": [
        {
          "@id": "scs:storage/LockingResourceStore#LockingResourceStore_source"
        },
        {
          "@id": "scs:storage/LockingResourceStore#LockingResourceStore_locks"
        }
      ]
```

If I add a random optional number to the interface instead I get 
```json
      "constructorArguments": [
        {
          "@id": "scs:storage/LockingResourceStore#LockingResourceStore_source"
        },
        {
          "fields": [
            {
              "keyRaw": "dummy",
              "value": {
                "@id": "scs:storage/LockingResourceStore#LockingResourceStore_locks_dummy"
              }
            }
          ]
        }
      ]
```
Which I guess is expected and makes sense.

-------------

The main issue of having an incorrect generated config file is that this makes it impossible to configure a LockingResourceStore. With the first example above I get the following error when using it in the server:
```
Error: Could not run config _:b0bnode111 because exactly one valid component type was expected, while 0 were found in the defined types []. Alternatively, the requireName and requireElement must be provided.
Found: Resource { value: '_:b0bnode111', termType: 'BlankNode' }
```
Which I guess is related to the empty fields array?

When adding a dummy function to get the correct generated config file the server starts up fine.

**Comment by rubensworks** [comment]
This should be fixed in 3.x
