### ISSUE TITLE
Make union types fallback to no range

### ISSUE THREAD

**Issue by rubensworks** [LinkedSoftwareDependencies/Components-Generator.js#56]
Currently, when using union types for parameters in the form of `string | number`, the generator will crash.

Instead, we should make these fallback to a parameter definition without `range`.
Optionally, we can emit a warning.

**Comment by woutermont** [comment]
What would this entail? They will be able to be generated, but not checked within a configuration?

**Comment by rubensworks** [comment]
Indeed, the generator will consider them as parameters, but the parameters will have no `range` value, which means that Components.js will do no type-checking for them at runtime.
