### ISSUE TITLE
Logging transport configuration

### ISSUE THREAD

**Issue by RobinDeBaets** [LinkedSoftwareDependencies/Components-Generator.js#6]
The logging framework we use, Winston, allows you to configure several methods, i.e. ways of displaying and saving logging statements: stdout, different files, different formats etc.

Maybe we should allow the CLI tool and Javascript methods to have control over this. This is not high-priority as the logger is mainly used for informing the end-user.

**Comment by rubensworks** [comment]
Not applicable anymore in rewrite.
