### ISSUE TITLE
Support constructor parameters of extended interface

### ISSUE THREAD

**Issue by joachimvh** [LinkedSoftwareDependencies/Components-Generator.js#73]
Not sure if this is a generator issue or components.js itself. Not even sure if this is an issue or if I'm missing something on how to do this.

Situation:
```typescript
export interface ArgsA {
  a: string;
}

export class ClassA {
  constructor(args: ArgsA) {}
}

export interface ArgsB extends ArgsA {
  b: number;
}

export class ClassB extends ClassA {
  constructor(args: ArgsB) {
    super(args);
  }
}
```

The problem is that I can't configure the `a` parameter for instances of `ClassB`. If I use `args_a` I get an `Invalid predicate IRI: args_a` error. If I use `ClassA:_args_a` I do not get an error but `a` is not defined. The only solution I have found so far is adding the `a` paramter to the `ArgsB` interface, but a solution where I do not have to copy the interface fields would be preferable.

**Comment by rubensworks** [comment]
Probably an issue with the generator indeed.

Problem is probably somewhere here where super interfaces are not being considered (even though they are loaded): https://github.com/LinkedSoftwareDependencies/Components-Generator.js/blob/5b7a93b42f773d9cd83a7f62a5de7d03a59bfe66/lib/parse/ParameterResolver.ts#L188-L192

**Comment by joachimvh** [comment]
I was just testing this out and the configs now work indeed ... but the constructors don't get the parameters.

Example I'm working on right now:
```json
{
  "@context": "https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/^2.0.0/components/context.jsonld",
  "@graph": [
    {
      "comment": "Handles the confirm interaction",
      "@id": "urn:solid-server:auth:password:ConfirmRoute",
      "@type": "ConfirmRoute",
      "BaseInteractionRouteArgs:_args_baseUrl": { "@id": "urn:solid-server:default:variable:baseUrl" },
      "BaseInteractionRouteArgs:_args_idpPath": "/idp/",
      "BaseInteractionRouteArgs:_args_relativePath": "/confirm/",
      "args_interactionCompleter": { "@type": "BaseInteractionCompleter" }
    }
  ]
}
```

```ts
export interface BaseInteractionRouteArgs {
  baseUrl: string;
  idpPath: string;
  relativePath: string;
}
```

```ts
export interface ConfirmArgs extends BaseInteractionRouteArgs {
  interactionCompleter: InteractionCompleter;
}

// ...
public constructor(args: ConfirmArgs)
```

`interactionCompleter` will be the only defined parameter in `args`. In case I change the `ConfirmArgs` interface to also have the extended parameters and remove the `BaseInteractionRouteArgs:_` part I do get the expected output.

Below is the generated file for the class:
```json
{
  "@context": [
    "https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/^2.0.0/components/context.jsonld"
  ],
  "@id": "npmd:@solid/community-server",
  "components": [
    {
      "@id": "scs:dist/identity/interaction/ConfirmRoute#ConfirmRoute",
      "@type": "Class",
      "requireElement": "ConfirmRoute",
      "extends": [
        "scs:dist/identity/interaction/routing/CompletingInteractionRoute#CompletingInteractionRoute"
      ],
      "comment": "Simple CompletingInteractionRoute that returns the session accountId as webId.",
      "parameters": [
        {
          "@id": "scs:dist/identity/interaction/ConfirmRoute#ConfirmRoute_args_interactionCompleter",
          "range": "scs:dist/identity/interaction/util/InteractionCompleter#InteractionCompleter",
          "unique": true,
          "required": true
        }
      ],
      "constructorArguments": [
        {
          "fields": [
            {
              "keyRaw": "interactionCompleter",
              "value": {
                "@id": "scs:dist/identity/interaction/ConfirmRoute#ConfirmRoute_args_interactionCompleter"
              }
            }
          ]
        }
      ]
    },
    {
      "@id": "scs:dist/identity/interaction/ConfirmRoute#ConfirmArgs",
      "@type": "AbstractClass",
      "requireElement": "ConfirmArgs",
      "extends": [
        "scs:dist/identity/interaction/routing/BaseInteractionRoute#BaseInteractionRouteArgs"
      ],
      "parameters": [],
      "constructorArguments": []
    }
  ]
}
```

Could it be that a reference to `ConfirmArgs` is missing from the `constructorArguments`? Or am I using this wrong?

**Comment by rubensworks** [comment]
Did you try this out with the `feature/comunica-2` or `feature/strict-type-checking` branch? Because this functionality hasn't been released yet. (will release betas in a sec, will ping you about that)

**Comment by joachimvh** [comment]
Ah I tried it out with the latest version (2.6.1) since I saw the issue was closed and assumed it was supposed to be fixed since I didn't receive the original errors any more. Will wait on a release then.
