### ISSUE TITLE
Avoid hardcoded components folder and add component to import list

### ISSUE THREAD

**Issue by RobinDeBaets** [LinkedSoftwareDependencies/Components-Generator.js#8]
To retrieve all component files of a module, we should open it's `components.jsonld` file and parse the `import` list in it. This is however far from easy because we need to take multiple things into consideration while converting these paths to local paths. 
An example of this is the `lsd:importPaths` option in the `package.json` which maps the IRI prefix to the local components folder.

Example: 
```json
{
  "@context": "https://linkedsoftwaredependencies.org/bundles/npm/@comunica/core/^1.0.0/components/context.jsonld",
  "@id": "npmd:@comunica/core",
  "@type": "Module",
  "requireName": "@comunica/core",
  "import": [
    "files-cc:components/ActionObserver.jsonld",
    "files-cc:components/Actor.jsonld",
    "files-cc:components/Bus.jsonld",
    "files-cc:components/BusIndexed.jsonld",
    "files-cc:components/Logger.jsonld",
    "files-cc:components/Mediator.jsonld"
  ]
}
```

Our current program searches through the hardcoded `components` folder and parses every `.jsonld` file. We should avoid this behaviour to match the real Components.js behaviour.

https://github.com/LinkedSoftwareDependencies/componentsjs-generator/blob/6eeedfef35a2ce15ce1016503fc277a1c72aaff3/lib/AstUtils.js#L129-L148

On top of this, in practice we should add the 'compacted' path of the newly generated `.jsonld` file to the `import` option as well. This is not yet implemented, but is very important if we want to fully automate this tool.

**Comment by rubensworks** [comment]
Not applicable anymore due to rewrite.
