### ISSUE TITLE
JSON range does not work on external type or any

### ISSUE THREAD

**Issue by joachimvh** [LinkedSoftwareDependencies/Components-Generator.js#82]
This is with version `3.0.0-beta.1`.

As discussed on mattermost.

I'm getting errors that the claims IRI is invalid here: https://github.com/solid/community-server/blob/main/config/identity/handler/provider-factory/identity.json#L18
but this is part of a JSON object defined here as `@range {json}` : https://github.com/solid/community-server/blob/main/src/identity/configuration/IdentityProviderFactory.ts#L76
and I have added Configuration to the `.componentsignore`

The generated range for that parameter is `"@type": "ParameterRangeUndefined"`. The same happens if the type is changed to `any`. If the type is changed to `Record<string, unknown>` the correct type is generated (`"rdf:JSON"`)

**Comment by rubensworks** [comment]
Should be fixed in 3.0.0-beta.1.
Should also be possible to remove that entry in `.componentsignore`.
